----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 2.0.0 Feb. 1, 2011
-- ?? 11? 13 2020 21:50:26
--
--      Input file      : 
--      Component name  : breath_led
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
   USE ieee.std_logic_1164.all;
   USE ieee.std_logic_unsigned.all;

ENTITY breath_led IS
   PORT (
      
      clk  : IN STD_LOGIC;
      rst  : IN STD_LOGIC;
      led  : OUT STD_LOGIC
   );
END breath_led;

ARCHITECTURE trans OF breath_led IS
   
   SIGNAL cnt1      : STD_LOGIC_VECTOR(24 DOWNTO 0);
   SIGNAL cnt2      : STD_LOGIC_VECTOR(24 DOWNTO 0);
   SIGNAL flag      : STD_LOGIC;
   
   CONSTANT CNT_NUM : INTEGER := 2400;
BEGIN
   
   PROCESS (clk, rst)
   BEGIN
      IF ((NOT(rst)) = '1') THEN
         cnt1 <= "0000000000000000000000000";
      ELSIF (clk'EVENT AND clk = '1') THEN
         IF (cnt1 >= (CNT_NUM - 1)) THEN
            cnt1 <= "0000000000000000000000000";
         ELSE
            cnt1 <= cnt1 + "1";
         END IF;
      END IF;
   END PROCESS;
   
   
   PROCESS (clk, rst)
   BEGIN
      IF ((NOT(rst)) = '1') THEN
         cnt2 <= "0000000000000000000000000";
         flag <= '0';
      ELSIF (clk'EVENT AND clk = '1') THEN
         IF (cnt1 = (CNT_NUM - 1)) THEN
            IF ((NOT(flag)) = '1') THEN
               IF (cnt2 >= (CNT_NUM - 1)) THEN
                  flag <= '1';
               ELSE
                  cnt2 <= cnt2 + "1";
               END IF;
            ELSE
               IF (cnt2 <= "0") THEN
                  flag <= '0';
               ELSE
                  cnt2 <= cnt2 - "1";
               END IF;
            END IF;
         ELSE
            
            cnt2 <= cnt2;
         END IF;
      END IF;
   END PROCESS;
   
   
   led <= '0' WHEN (cnt1 < cnt2) ELSE
          '1';
   
END trans;


