/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 4.2 */
/* c:/lscc/diamond/3.11_x64/ispfpga/bin/nt64/scuba.exe -w -n mult_5u_5u -lang verilog -bb -arch xo2c00 -type dspmult -pfu_mult -widtha 5 -widthb 5 -widthp 10 -pl_stages 0  */
/* Mon Nov 23 12:00:55 2020 */


`timescale 1 ns / 1 ps
module mult_5u_5u (A, B, P)/* synthesis NGD_DRC_MASK=1 */;
    input wire [4:0] A;
    input wire [4:0] B;
    output wire [9:0] P;

    wire scuba_vhi;
    wire mult_5u_5u_0_pp_0_0;
    wire s_mult_5u_5u_0_0_2;
    wire mult_5u_5u_0_pp_1_2;
    wire s_mult_5u_5u_0_0_3;
    wire co_mult_5u_5u_0_0_1;
    wire co_mult_5u_5u_0_0_2;
    wire co_mult_5u_5u_0_0_3;
    wire co_mult_5u_5u_0_0_4;
    wire mult_5u_5u_0_pp_2_4;
    wire s_mult_5u_5u_0_0_4;
    wire co_t_mult_5u_5u_0_1_1;
    wire mult_5u_5u_0_pp_2_5;
    wire mult_5u_5u_0_pp_2_6;
    wire s_mult_5u_5u_0_0_5;
    wire s_mult_5u_5u_0_0_6;
    wire co_t_mult_5u_5u_0_1_2;
    wire mult_5u_5u_0_pp_2_7;
    wire mult_5u_5u_0_pp_2_8;
    wire s_mult_5u_5u_0_0_7;
    wire s_mult_5u_5u_0_0_8;
    wire co_t_mult_5u_5u_0_1_4;
    wire co_t_mult_5u_5u_0_1_3;
    wire s_mult_5u_5u_0_0_9;
    wire mult_5u_5u_0_pp_0_2;
    wire mult_5u_5u_0_pp_0_1;
    wire mult_5u_5u_0_cin_lr_0;
    wire mult_5u_5u_0_pp_0_4;
    wire mult_5u_5u_0_pp_0_3;
    wire mco;
    wire mfco;
    wire mult_5u_5u_0_pp_0_6;
    wire mult_5u_5u_0_pp_0_5;
    wire mco_1;
    wire mult_5u_5u_0_pp_1_4;
    wire mult_5u_5u_0_pp_1_3;
    wire mult_5u_5u_0_cin_lr_2;
    wire mult_5u_5u_0_pp_1_6;
    wire mult_5u_5u_0_pp_1_5;
    wire mco_2;
    wire mfco_1;
    wire mult_5u_5u_0_pp_1_8;
    wire mult_5u_5u_0_pp_1_7;
    wire mco_3;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    AND2 AND2_t6 (.A(A[0]), .B(B[0]), .Z(mult_5u_5u_0_pp_0_0));

    AND2 AND2_t5 (.A(A[0]), .B(B[2]), .Z(mult_5u_5u_0_pp_1_2));

    AND2 AND2_t4 (.A(A[0]), .B(B[4]), .Z(mult_5u_5u_0_pp_2_4));

    AND2 AND2_t3 (.A(A[1]), .B(B[4]), .Z(mult_5u_5u_0_pp_2_5));

    AND2 AND2_t2 (.A(A[2]), .B(B[4]), .Z(mult_5u_5u_0_pp_2_6));

    AND2 AND2_t1 (.A(A[3]), .B(B[4]), .Z(mult_5u_5u_0_pp_2_7));

    AND2 AND2_t0 (.A(A[4]), .B(B[4]), .Z(mult_5u_5u_0_pp_2_8));

    FADD2B mult_5u_5u_0_cin_lr_add_0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(mult_5u_5u_0_cin_lr_0), .S0(), 
        .S1());

    FADD2B mult_5u_5u_0_cin_lr_add_2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(mult_5u_5u_0_cin_lr_2), .S0(), 
        .S1());

    FADD2B Cadd_mult_5u_5u_0_0_1 (.A0(scuba_vlo), .A1(mult_5u_5u_0_pp_0_2), 
        .B0(scuba_vlo), .B1(mult_5u_5u_0_pp_1_2), .CI(scuba_vlo), .COUT(co_mult_5u_5u_0_0_1), 
        .S0(), .S1(s_mult_5u_5u_0_0_2));

    FADD2B mult_5u_5u_0_add_0_2 (.A0(mult_5u_5u_0_pp_0_3), .A1(mult_5u_5u_0_pp_0_4), 
        .B0(mult_5u_5u_0_pp_1_3), .B1(mult_5u_5u_0_pp_1_4), .CI(co_mult_5u_5u_0_0_1), 
        .COUT(co_mult_5u_5u_0_0_2), .S0(s_mult_5u_5u_0_0_3), .S1(s_mult_5u_5u_0_0_4));

    FADD2B mult_5u_5u_0_add_0_3 (.A0(mult_5u_5u_0_pp_0_5), .A1(mult_5u_5u_0_pp_0_6), 
        .B0(mult_5u_5u_0_pp_1_5), .B1(mult_5u_5u_0_pp_1_6), .CI(co_mult_5u_5u_0_0_2), 
        .COUT(co_mult_5u_5u_0_0_3), .S0(s_mult_5u_5u_0_0_5), .S1(s_mult_5u_5u_0_0_6));

    FADD2B mult_5u_5u_0_add_0_4 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(mult_5u_5u_0_pp_1_7), 
        .B1(mult_5u_5u_0_pp_1_8), .CI(co_mult_5u_5u_0_0_3), .COUT(co_mult_5u_5u_0_0_4), 
        .S0(s_mult_5u_5u_0_0_7), .S1(s_mult_5u_5u_0_0_8));

    FADD2B Cadd_mult_5u_5u_0_0_5 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co_mult_5u_5u_0_0_4), .COUT(), .S0(s_mult_5u_5u_0_0_9), 
        .S1());

    FADD2B Cadd_t_mult_5u_5u_0_1_1 (.A0(scuba_vlo), .A1(s_mult_5u_5u_0_0_4), 
        .B0(scuba_vlo), .B1(mult_5u_5u_0_pp_2_4), .CI(scuba_vlo), .COUT(co_t_mult_5u_5u_0_1_1), 
        .S0(), .S1(P[4]));

    FADD2B t_mult_5u_5u_0_add_1_2 (.A0(s_mult_5u_5u_0_0_5), .A1(s_mult_5u_5u_0_0_6), 
        .B0(mult_5u_5u_0_pp_2_5), .B1(mult_5u_5u_0_pp_2_6), .CI(co_t_mult_5u_5u_0_1_1), 
        .COUT(co_t_mult_5u_5u_0_1_2), .S0(P[5]), .S1(P[6]));

    FADD2B t_mult_5u_5u_0_add_1_3 (.A0(s_mult_5u_5u_0_0_7), .A1(s_mult_5u_5u_0_0_8), 
        .B0(mult_5u_5u_0_pp_2_7), .B1(mult_5u_5u_0_pp_2_8), .CI(co_t_mult_5u_5u_0_1_2), 
        .COUT(co_t_mult_5u_5u_0_1_3), .S0(P[7]), .S1(P[8]));

    FADD2B t_mult_5u_5u_0_add_1_4 (.A0(s_mult_5u_5u_0_0_9), .A1(scuba_vlo), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co_t_mult_5u_5u_0_1_3), .COUT(co_t_mult_5u_5u_0_1_4), 
        .S0(P[9]), .S1());

    MULT2 mult_5u_5u_0_mult_0_0 (.A0(A[0]), .A1(A[1]), .A2(A[1]), .A3(A[2]), 
        .B0(B[1]), .B1(B[0]), .B2(B[1]), .B3(B[0]), .CI(mult_5u_5u_0_cin_lr_0), 
        .P0(mult_5u_5u_0_pp_0_1), .P1(mult_5u_5u_0_pp_0_2), .CO(mco));

    MULT2 mult_5u_5u_0_mult_0_1 (.A0(A[2]), .A1(A[3]), .A2(A[3]), .A3(A[4]), 
        .B0(B[1]), .B1(B[0]), .B2(B[1]), .B3(B[0]), .CI(mco), .P0(mult_5u_5u_0_pp_0_3), 
        .P1(mult_5u_5u_0_pp_0_4), .CO(mco_1));

    MULT2 mult_5u_5u_0_mult_0_2 (.A0(A[4]), .A1(scuba_vlo), .A2(scuba_vlo), 
        .A3(scuba_vlo), .B0(B[1]), .B1(B[0]), .B2(B[1]), .B3(B[0]), .CI(mco_1), 
        .P0(mult_5u_5u_0_pp_0_5), .P1(mult_5u_5u_0_pp_0_6), .CO(mfco));

    MULT2 mult_5u_5u_0_mult_2_0 (.A0(A[0]), .A1(A[1]), .A2(A[1]), .A3(A[2]), 
        .B0(B[3]), .B1(B[2]), .B2(B[3]), .B3(B[2]), .CI(mult_5u_5u_0_cin_lr_2), 
        .P0(mult_5u_5u_0_pp_1_3), .P1(mult_5u_5u_0_pp_1_4), .CO(mco_2));

    MULT2 mult_5u_5u_0_mult_2_1 (.A0(A[2]), .A1(A[3]), .A2(A[3]), .A3(A[4]), 
        .B0(B[3]), .B1(B[2]), .B2(B[3]), .B3(B[2]), .CI(mco_2), .P0(mult_5u_5u_0_pp_1_5), 
        .P1(mult_5u_5u_0_pp_1_6), .CO(mco_3));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    MULT2 mult_5u_5u_0_mult_2_2 (.A0(A[4]), .A1(scuba_vlo), .A2(scuba_vlo), 
        .A3(scuba_vlo), .B0(B[3]), .B1(B[2]), .B2(B[3]), .B3(B[2]), .CI(mco_3), 
        .P0(mult_5u_5u_0_pp_1_7), .P1(mult_5u_5u_0_pp_1_8), .CO(mfco_1));

    assign P[0] = mult_5u_5u_0_pp_0_0;
    assign P[1] = mult_5u_5u_0_pp_0_1;
    assign P[2] = s_mult_5u_5u_0_0_2;
    assign P[3] = s_mult_5u_5u_0_0_3;


    // exemplar begin
    // exemplar end

endmodule
