/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 4.2 */
/* Mon Nov 23 12:00:55 2020 */

/* parameterized module instance */
mult_5u_5u __ (.A( ), .B( ), .P( ));
