//Verilog testbench template generated by SCUBA Diamond (64-bit) 3.11.0.396.4
`timescale 1 ns / 1 ps
module tb;
    reg [4:0] A = 5'b0;
    reg [4:0] B = 5'b0;
    wire [9:0] P;

    integer i0 = 0, i1 = 0, i2 = 0;

    GSR GSR_INST (.GSR(1'b1));
    PUR PUR_INST (.PUR(1'b1));

    mult_5u_5u u1 (.A(A), .B(B), .P(P)
    );

    initial
    begin
       A <= 0;
      for (i1 = 0; i1 < 200; i1 = i1 + 1) begin
        #10;
         A <= A + 1'b1;
      end
    end
    initial
    begin
       B <= 0;
      for (i2 = 0; i2 < 200; i2 = i2 + 1) begin
        #10;
         B <= B + 1'b1;
      end
    end
endmodule